name: fridgematch
description: FridgeMatch - Your personal chef that knows your fridge, your health, and your culture.
publish_to: none
version: 1.0.2+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.3.1
  sqflite: ^2.4.1
  fl_chart: ^0.69.2
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/meals.json
    - assets/ingredients.json
